---
- hosts: web
  tasks:
  - name: Removing Fal2ban
    command: chdir=/etc/logrotate.d/ rm -rf fail2ban
    register: DeleteFail2ban_output
    sudo: yes

  - name: what got registered
    debug: var=DeleteFail2ban_output

  - name: return code
    debug: msg="return code was {{ DeleteFail2ban_output['rc'] }}"
    
  - name: Copy in fail2ban configuration
    copy: src=/fail2ban  dest=/etc/logrotate.d/fail2ban
    register: Fail2Ban_config_output
    sudo: yes

  - name: what got registered
    debug: var=Fail2Ban_config_output

 